### ISSUE TITLE
Docker MongoDB setup

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#1]
Setup a docker file launching MongoDB and your python project.

**Comment by henderkes** [comment]
[Dockerfile.txt](https://github.com/Drakulix/knex/files/998609/Dockerfile.txt)
[first.py.txt](https://github.com/Drakulix/knex/files/998606/first.py.txt)

remove the .txt file extension

**Comment by Drakulix** [comment]
Please provide a merge request adding those files to the repository. @DubbleClick
