### ISSUE TITLE
[BE] Test inconsistent delete

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#100]
- Shutdown one DB container (mongo or ES)
- Then delete
- Test for error
- Start container again

`test_unconsistent_delete` in `TestDELETE` in `tests/api/test_projects.py`

**Comment by Leats** [comment]
When elasticsearch is shut down and something is deleted:
Once elasticsearch is back, should the mongo-connector update it? 
Or what error should be given out?
