### ISSUE TITLE
[BE] Test post project search

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#107]
Post elastic search query to /api/projects/search

verify results

**Comment by Leats** [comment]
Uh, I'm not sure I'm doing the queries in the right way? 
I tried both doing one where it should find the right file and one where (as far as I understood?) it should find none (match_none). 
It is not sorted and both gives the same thing back.
So... either the post is not working or **my** query is not working at all.

[(see branch here)](https://github.com/Drakulix/knex/tree/feature/backend/AdditionalTests)

**Comment by henderkes** [comment]
@Leats whats the status of this?

**Comment by Leats** [comment]
Since search post is not used at all this issue is not active anymore.
