### ISSUE TITLE
[BE] Setup User Model for Flask-Security

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#108]
Setup `users` collection in MongoDB

User fields:
    - first name
    - last name
    - mail
    - password_hash
    - bio (string)
    - bookmarks (array of uuid)

Setup model for FlaskSecurity

**Comment by aTepliak** [comment]
I suppose there is a json validator for this colllection needed
should the password be hashed withing the insert_user function?

insert_user is just a prototype I used for testing

**Comment by Drakulix** [comment]
1. Yes a validator will be needed, but that *can* be postponed to a later time, because we need this rather sooner then later
2. Yes it should be hashed, but again this *may* be postponed to have something to work with.

**Comment by henderkes** [comment]
This comes in closely with #126 and the referenced issues, feel free to contribute to the branch instead of rewriting already existing code
