### ISSUE TITLE
[BE] Add new user api endpoints

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#113]
PUT /api/users -> Create user if admin, return id
PUT /api/users/<id> -> Update user if authenticated user is admin
GET /api/users/<id> get information about user (login_required only for now)
POST /api/users/login -> Login call to FlaskSecurity
POST /api/users/logout -> Logout call

**Comment by henderkes** [comment]
please check #126 
I came across built-in flask-security (or flask-login/admin) login templates, might be worth looking into

**Comment by Drakulix** [comment]
We don't want any templates, that is part of the frontend. We just want a body with username and password and confirmation from flask-security. REST calls, just like the rest.

**Comment by henderkes** [comment]
sorry, I should have elaborated. what's worth looking into is how the login works, not to create or modify a visualisation template to display a page
