### ISSUE TITLE
Import of list of manifests in json5 format fails

### ISSUE THREAD

**Issue by Krisselchen** [Drakulix/knex#117]
Error Message from Validator:
"error: 'TypeError' object has no attribute 'message'"

**Comment by markwitz** [comment]
@Krisselchen  can u help me recreate this i can't maybe this is fixed in the new version on master`?

**Comment by Krisselchen** [comment]
@markwitz I can't recreate it either. It seems to work now.

**Comment by markwitz** [comment]
closed because it seems to be fixed
