### ISSUE TITLE
`http://localhost:5000/api/projects` returns wrong uuid

### ISSUE THREAD

**Issue by gitmirgut** [Drakulix/knex#122]
It is not possible to run **GET:**`http://localhost:5000/api/projects/uuid:project_id` with `uuid`'s returned from **GET:**`http://localhost:5000/api/projects`.
The returned `uuid`'s are similar to `b0dcf91bff5b4b27bc0db2dcfe343e70`, but they have to look like this
`b0dcf91b-ff5b-4b27-bc0d-b2dcfe343e70`
:x: `http://localhost:5000/api/projects/b0dcf91bff5b4b27bc0db2dcfe343e70`
:white_check_mark: `http://localhost:5000/api/projects/b0dcf91b-ff5b-4b27-bc0d-b2dcfe343e70`

**Comment by henderkes** [comment]
fixed in pr #124
