### ISSUE TITLE
[BE] Content-Type Header doesn't get checked (POSTing to /api/projects)

### ISSUE THREAD

**Issue by Leats** [Drakulix/knex#127]
When POSTing to _/api/projects_ with Content-Type Header != "application/json" or "application/json5", __but__ a valid JSON it should return a 400 Bad Request because of the wrong header.

However, it does return a 200. 

(Referencing test from issue #97 and written test, which is currently in pull request #123 )

**Comment by henderkes** [comment]
How can this produce a 200 status code if that is nowhere in the code?
It currently stores valid jsons anyway no matter the content header.

**Comment by Drakulix** [comment]
200 is default, if you return something successfully @DubbleClick

**Comment by henderkes** [comment]
oh, in that case our error handling was simply shit, rewrote this quickly to raise an exception instead of returning a response

**Comment by Leats** [comment]
@DubbleClick Was this one fixed as well? I thought only #128 was fixed, or did you close the wrong issue? Because in the master branch the test_misformed_content_type test still fails. test_empty_post is passing.

**Comment by Drakulix** [comment]
Reopen until this is verified as fixed.

**Comment by henderkes** [comment]
Actually, we cannot return a 400 error if the content header is not application/json(5) as the file upload will kick in then, I will check for no files and wrong content header then

**Comment by henderkes** [comment]
should be fixed, please test @Leats

**Comment by Leats** [comment]
Fixed, thank you!
