### ISSUE TITLE
[BE] Test and potentially fix non utf-8 encoded request bodies

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#133]
Currently passing non utf-8 encoded request bodies should result in a 500 Internal Server Error, because they are most likely raising an exception.

This should be checked by tests, because this should instead result in a 400 (Bad Request) and be fixed, if this is actually an issue.

For functions hit by this problem search for `.decode('utf-8')` calls.

**Comment by henderkes** [comment]
I will have to change the content-type checks for this, with a specific encoding that should usually be specified in there, too.

**Comment by henderkes** [comment]
request.data is generally unformatted (type: str, not unicode or bytes) in python3
therefore the first and only way to check it is to see if decode('utf-8') throws an exception and catch the correct one.

**Comment by Drakulix** [comment]
Yes, but currently this will result in an internal server error. I just want that exception to be catched and then returned as an 400 status code

**Comment by henderkes** [comment]
It was previously caught as a general exception, fixed now.
