### ISSUE TITLE
[REQUIRED] JSON schema needs another url field.

### ISSUE THREAD

**Issue by Rintel** [Drakulix/knex#136]
Right now we only have an url string in the JSON schema. 
As we wanna add more than only one url it would be great to replace the url field by an array or even an object field.

**Comment by Drakulix** [comment]
That should already be allowed. Please test and report back.

**Comment by henderkes** [comment]
From manifest_schema.json5:
`"url": [
    "www.github.com/knex/"
  ],`

**Comment by Rintel** [comment]
Okay, thanks for the information. I'm gonna check and will come back to it.

**Comment by Rintel** [comment]
works
