### ISSUE TITLE
Python Testing Framework

### ISSUE THREAD

**Issue by Leats** [Drakulix/knex#14]
Decide on which testing framework to use:

According to [Flask's docs](http://flask.pocoo.org/docs/0.12/testing/) "Flask provides a way to test your application by exposing the Werkzeug test Client and handling the context locals for you. You can then use that with your favourite testing solution."
So we should be rather free in whatever framework we use.
The docs itself uses unittest as an example on how to do it.

[__unittest__](https://docs.python.org/2/library/unittest.html): unit test framework included in Python standard library, practical if users have experience with xUnit frameworks
Links: [Introduction to unittest](http://pythontesting.net/framework/unittest/unittest-introduction/)
 [Basic Example](https://docs.python.org/2/library/unittest.html#basic-example)

[__pytest__](https://docs.pytest.org/en/latest/): not in standard library, more extensive test-discovery than the simple one unittest has, you need in general less code lines to write the tests, able to run unittest style tests [x](https://docs.pytest.org/en/latest/unittest.html)
Links: [Introduction to pytest](http://pythontesting.net/framework/pytest/pytest-introduction/)

A third rather popular option seemed to be nose, however that one is not further developed and from what I've read most people switched to pytest, and some to unittest.

In the end both seem to be of use, they have different advantages, though from what I've seen pytest seems to be the most popular, and it was actually recommended to me by a friend who has already worked with flask together with pytest.

If anyone else has any recommendations or has already any experience with any of these (or something else) please feel free to share

**Comment by henderkes** [comment]
It was decided to use pytest in the last meeting.
