### ISSUE TITLE
[BE] Followup for #127 #140

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#141]
Sorry @DubbleClick but with your rather quick merge, *you* got yourself a new task.

1. Make sure json5 data does not pass when 'application/json' is the given mime-type.
2. Make sure json data is still passing when 'application/json5' is the given mime-type.
3. Write some tests to prove both cases.

**Comment by Leats** [comment]
Sorry for approving too early, I can write the tests if that hasn't already happened? :(

**Comment by henderkes** [comment]
I planned on doing it tomorrow but feel free to

**Comment by henderkes** [comment]
edit: mobile github site doesn't let me remove the bug label.

1) and 2) are already the case, I actually tested 2) before, unittests are still a good idea. 1) is logic wise proven correct, too, as uploader.save_manifest_to_db(request.json) will throw an exception with json5 data

**Comment by Drakulix** [comment]
But an exception really is not the way to go here. This should not pass in the first place.

**Comment by henderkes** [comment]
If not an exception, what should happen if json5 content is supplied with 'application/json' header? How would we check if it's valid json without parsing it first, which in the end will throw the exception?

**Comment by Drakulix** [comment]
We should throw an exception but you should not try to access request.data and try to parse it, if the content-type is set to `application/json`

**Comment by Leats** [comment]
Added tests in #143 , which run through as I think they should.

**Comment by henderkes** [comment]
@Drakulix we don't, if 'application/json' is set request.json will not be empty. If it is not empty, the 'elif' will never be executed.

**Comment by Drakulix** [comment]
No, if 'application/json' is set, but request.json cannot be parsed by flask, it will no be set.

**Comment by henderkes** [comment]
I was under the impression only get_json() method would try to parse it. Let me confirm.

Edit you are right, I will fix this asap.
