### ISSUE TITLE
[BE] User api - Configure flask security to hash the passwords for us.

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#163]
Don't hash manually, but use the functionality flask-security may provide. See [`configuration`](https://pythonhosted.org/Flask-Security/configuration.html) and `utils.encrypt_password()` for updating the user manually (#162)

**Comment by henderkes** [comment]
don't forget the password salt, must be configured if a hashing config is set

**Comment by henderkes** [comment]
@pdler whats the current status?

**Comment by Drakulix** [comment]
This was fixed for sure.
