### ISSUE TITLE
[BE] Test Mongo & ES consistency

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#164]
Write tests that pushes a manifest into the backend and verify that the results are in mongoDB and in ElasticSearch and that they are equal to the inserted body.

**Comment by henderkes** [comment]
I'm not sure if they can be equal with the _id issue. I'll test around and report how mongo-connector handles that

**Comment by Drakulix** [comment]
then test if they are equal except the id, an empty body should not be allowed anymore.

**Comment by markwitz** [comment]
How is the work going here? i need this to test the connector #161 or should i maybe write those?

**Comment by henderkes** [comment]
as said in slack, I will only be able to dedicate time to the project on the weekend, sorry

**Comment by markwitz** [comment]
i will start on this in the Backend/feature/mongo-connector/iss87 branch because i'll need the testing there
#87
