### ISSUE TITLE
[BE] Write tests for the new user api endpoints

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#165]
- [x] test login/logout
- [x] test accessing a `@login_required` route with and without login
- [x] test create user without login, with normal user and with admin
- [x] test update user without login, with normal user, with same user and with admin

**Comment by aTepliak** [comment]
update user seem not to work properly

**Comment by aTepliak** [comment]
see branch  test_security/iss165 #184

**Comment by DubbleClick** [comment]
#184
