### ISSUE TITLE
[BE] test soundclouds json5 data

### ISSUE THREAD

**Issue by henderkes** [Drakulix/knex#183]
its in the evalData folder, just upload it using a multi file submit and check if any don't work

or use the python script in the folder

**Comment by Krisselchen** [comment]
I thought the data should not be in there because of secrecy. Didn't we determine that? Or should I put the correct data in here? At the moment it is in the dropbox. @Drakulix

**Comment by henderkes** [comment]
I haven't heard of that, if it's the case we should probably remove it
