### ISSUE TITLE
[BE] Add api endpoints to add,get,remove bookmarks

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#189]
- [x] POST /api/users/bookmarks/<id:uuid>
- [x] DELETE /api/users/bookmarks/<id:uuid>

**Comment by Drakulix** [comment]
@Rintel Does a separate get_bookmarks endpoint make any sense? They are part of the get_user endpoint anyway.

**Comment by Rintel** [comment]
@Drakulix If that's already part of the get_user endpoint, I don't see any reason for it.
