### ISSUE TITLE
[BE] Add notification field to user

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#194]
Add list of notifications (id, title, description, link) to user collection

**Comment by aTepliak** [comment]
should it be a list  or a list of dictionaries?

**Comment by aTepliak** [comment]
could you tell me please, what is ment by id?  user id (email)?

**Comment by aTepliak** [comment]
I hope I understand it correctly.
I was trying to find an example how to nest dicField into listField, but that is almost impossible to update later. Therefore I define :
```
class Notification():
    id =  DB.StringField(max_length=255)
    title = DB.StringField(max_length=255)
    description =  DB.StringField(max_length=255)
    link = DB.URLField();
     
    
class User(DB.Document, UserMixin):
    email = DB.StringField(max_length=255)
    ...
    notifications = DB.EmbeddedDocumentListField(Notification)
 

```
and then change respective things in users.py.
