### ISSUE TITLE
Example JSON file + validator

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#2]
Create some example json files (not final format) and start implementing a basic validator.

**Comment by markwitz** [comment]
i could use some help writing the unit tests and discussing the manifest overall

**Comment by Drakulix** [comment]
Do you have something to show off already?

**Comment by markwitz** [comment]
i guess so but i still got problems handling multible  ValidationError ' s as an Exception
Because all errors are recorded and accessible throug the validators iter_errors method but only one it thrown as an Exception.

**Comment by markwitz** [comment]
a sample of how a json file could look like is:
```json
{
  "project":
  {
    "title": "test_project",
    "url": "www.github.com/knex/",
    "analysis":
    {
      "url": "here-you-find-the-analysis.com",
      "description": "thats what this analysis is about"
    },
    "authors":
    [
      {
      "name": "test_owner",
      "email": "email@address.com"
      }
    ],
    "team":
    {
      "team_name": "teamname",
      "members":
      [
        {
          "name": "member1",
          "email": "member1@team.com"
        },
        {
          "name": "member2",
          "email": "member2@team.com"
        }
      ]
    },
    "status": "DONE",
    "description": "can this be a multiline description?",
    "date_creation": "1970-01-01",
    "date_last_updated": "2017-05-11",
    "tags":
    [
      "tag",
      "bio"
    ],
    "future_work":
    [
      {
        "title": "this is something related to this work",
        "author": "the_author_of_this_awesome_work",
        "email": "email@example.com",
        "description": "some description of the work that will be done in the future"
      }
    ],
    "related_projects":
    [
      {
        "id": 0,
        "name": "name of the listed project",
        "author": "author",
        "url": "www.my.url"
      }
    ]
  }
}```

**Comment by markwitz** [comment]
Okay the question is  what do we do with the sample introduced by s. ? Do we implement their model or do we merge the ideas together?

**Comment by Drakulix** [comment]
They said, it can be adjusted. I would go with merge.

**Comment by markwitz** [comment]
```json

# JSON TEMPLATE:
{
   "title": "xxx",
   "authors": [
      {
         "name": "xxx", "email": "xxx"
      }
   ],
   "teams": [
      {
         "name": "xxx"
      }
   ],
   "status": "xxx",
   "description": "xxx",
   "hypothesis": "",
   "future_work": "xxx",
   "tags": [ "xxx" ],
   "dependencies": [
      {
         "project_id": "xxx"
      }
   ]
}

```
that is ne proposed structure of the json we got send. I think we should merge the ideas but don't loose to many fields because it will make searches much harder. 
I'm not sure if dependencies is covered in related_projects because it could somehow be used differently

**Comment by markwitz** [comment]
@aTepliak need tests for file not found
or invalid json

**Comment by Drakulix** [comment]
@markwitz evaluate json5, write example, send to soundcloud.

**Comment by markwitz** [comment]
I got Problems with json5 in Python 3.2 ...do er have to support that version if we gonna run docket with maybe a later version anyways?

**Comment by Drakulix** [comment]
No, we can just drop support for that.
We did only guarantee the latest stable version.

**Comment by markwitz** [comment]
ok

**Comment by JamesComey** [comment]
@markwitz @Drakulix Is the example still up to date?
