### ISSUE TITLE
create "knex" logo

### ISSUE THREAD

**Issue by Rintel** [Drakulix/knex#20]
Colour Codes:

Black: #333333
Orange: #FF5500

Image Type: PNG
Size: ~600px Width

It would be perfect if you directly upload (commit) the image into the folder web/style/img

Name: knex_logo.png

**Comment by Leats** [comment]
Added logo, if there are any problems or things you'd like different please tell me.
Even if you'd like a different logo altogether

**Comment by Rintel** [comment]
I think it's perfect right now, we come back to it when the team demands it.
