### ISSUE TITLE
[BE] Add archive flag to projects

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#201]
Add archive flag to projects collection

**Comment by henderkes** [comment]
should we also define this as an optional field in the schema, or should we delete it when exporting a json?

**Comment by Drakulix** [comment]
It should be an optional field, so that the projects archived-state does not get removed on export/import.

**Comment by aTepliak** [comment]
would a new  boolean field in jsonschma validator suite:
`{ "archived": "boolean" }`  ?

**Comment by Drakulix** [comment]
Yes I think so.

**Comment by henderkes** [comment]
Yes, that's right. Shouldn't forget adding to to one of the manifests and the schema too

**Comment by Drakulix** [comment]
Not to the manifests, this should be an optional flag.

**Comment by henderkes** [comment]
Yes, but to one of the manifests to be able to include it in a test. Achieving functionality should be tested for both imports and updated projects.

**Comment by aTepliak** [comment]
Doesn't the "manifest_schema.json" validate everything itself?
There is also an array with key 'required' , that defines all fields there as required  (and all not in there as optional)

**Comment by henderkes** [comment]
Yes, the archived flag must be an optional field. We should add the archive flag to one of the test jsons though and try to search for it after import, which should return not found (unless searched with the archived flag).

Unless we don't want pytest to test archiving functionality?

**Comment by Drakulix** [comment]
Yes you are right and we want to test that as well.

**Comment by markwitz** [comment]
is some one working on this? and where? otherwise i would start working here @aTepliak

**Comment by aTepliak** [comment]
@markwitz  yes, feel free to do it

**Comment by markwitz** [comment]
only admins and users mentioned in the manifest should be able to achive?

**Comment by markwitz** [comment]
I see a problem here with our search indexing archived projects if they are in the same collection

**Comment by Drakulix** [comment]
Thats not a problem, but a feature, they shall be searchable, just not by default, which is something the search api needs to provide.

**Comment by Drakulix** [comment]
Also for your first question @markwitz. Yes

**Comment by henderkes** [comment]
Yeah the default search call will just have to be updated to have "archived" : "false" or no "archived" entry at all.
