### ISSUE TITLE
[FE] Click on author in project discovery leads to his user profile

### ISSUE THREAD

**Issue by Rintel** [Drakulix/knex#208]
If a user is already in the system, he should be highlighted in the "ProjectDetails" among the Authors and also in the discovery tables in the tab "Authors". A click on the highlighted user leads to his users profile page. (pass the user id or e-mail to the profile details view and fetch the information before rendering)

**Comment by Rintel** [comment]
@gitmirgut I think @JamesComey has implemented that already but did not assign hisself to the ticket.

**Comment by JamesComey** [comment]
Hey guys I am working on the complete Project view now. Don't worry about it, it will be fine until sunday^^

**Comment by JamesComey** [comment]
Is the linking already working? If yes I will reuse that code in the new Project view
