### ISSUE TITLE
[FE/BE] Bugs when no projects are online

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#222]
The interface seems quite broken, when no projects are in the database.
The backend fails with ES "index_not_found" errors and the discovery page looks incomplete.
Adding projects via "create new project" also does not seem to work.

We need to address this before milestone 3.

Pinging @Rintel for communicating this problem to the frontend team.

@markwitz @DubbleClick Both of you have had the joy of configurating mongo-connector, this seems to be a bit related, we need to figure out, whats required to get the search to work (empty result) without an index. The index is only created by the connector, if a projects is added to that index. Maybe one of you has a good idea?

**Comment by henderkes** [comment]
Well, create the index and the collection manually upon setup if they don't exist, that should most definitely fix the problem

**Comment by Drakulix** [comment]
Still that needs to be done.

**Comment by henderkes** [comment]
backend wise this is fixed now, Frontend matter is still present

**Comment by Drakulix** [comment]
Needs to be tested at least.
