### ISSUE TITLE
[FE] Edit Project does not passes data to view

### ISSUE THREAD

**Issue by Rintel** [Drakulix/knex#225]
How to reproduce:

1. Click on any project title in "Project Discovery"
2. On the project detail view click the edit button in the upper right corner (pencil) 
3. Notice that the form stays empty

**Comment by Rintel** [comment]
@suzanap Have a look, thanks.

**Comment by suzanap** [comment]
This is because of the delay that is caused by ElasticSearch/mongo-connector. @Drakulix knows about this problem

**Comment by Drakulix** [comment]
Is it? @suzanap 
Cause I am getting errors in the console almost immediately.

![screenshot_2017-06-24t18 05 26 537551648 02 00](https://user-images.githubusercontent.com/4404502/27509950-bd271260-5907-11e7-87e8-9b49df38cfae.png)

**Comment by suzanap** [comment]
@Drakulix I don't get this error. Could you exactly describe what you do in order to get this? What I actually  get is this one: 
![image](https://user-images.githubusercontent.com/28600681/27510141-02f8ca7e-590b-11e7-816e-3640039491c1.png)
 After some time, it is loaded.

**Comment by Drakulix** [comment]
Must have been an outdated branch. I cannot even reproduce the original error anymore, I am not having any slow downs.
