### ISSUE TITLE
[BE] PUT-Update-request doesn't work anymore

### ISSUE THREAD

**Issue by suzanap** [Drakulix/knex#229]
When trying to update a project with Postman, the following error is received: 
{
    "message": "name 'ReturnDocument' is not defined",
    "validation_error": null
}
In devtools I get this: 
![image](https://user-images.githubusercontent.com/28600681/27510872-f8a07d74-5919-11e7-98e7-7a453c5d1d7e.png)

**Comment by Drakulix** [comment]
Closed via #234
