### ISSUE TITLE
[BE] PUT with invalid ID raises 405 instead of 404

### ISSUE THREAD

**Issue by Leats** [Drakulix/knex#231]
As currently seen in Pull Request #230, PUTting an invalid ID does return a _405 - Method Not Allowed_ instead of a 404.

**Comment by Leats** [comment]
okay, apparently this is correct, I was confused because with GET there was still a 404. Sorry.

**Comment by Krisselchen** [comment]
That is correct. The PUT Method is allowed for /api/projects/uuid and not for any string.
