### ISSUE TITLE
[BE] Add endpoint to get tags

### ISSUE THREAD

**Issue by Rintel** [Drakulix/knex#251]

**Comment by Drakulix** [comment]
This is needed for auto-completion, this should just get all existing tags, de-duplicated from all projects.

This should be quite straight-forward using [`distinct`](https://docs.mongodb.com/manual/reference/method/db.collection.distinct/)

**Comment by Drakulix** [comment]
List of all tags for a specific user. Should also be doable with `distinct` though it's query argument.

**Comment by henderkes** [comment]
done in #286
