### ISSUE TITLE
[BE] Users can execute admin only stuff

### ISSUE THREAD

**Issue by henderkes** [Drakulix/knex#259]
fix and test this in unauthorized delete test

**Comment by henderkes** [comment]
with @roles_required('admin) -> 404, with @admin_permission.require() -> 500
shouldn't the test return 403 in either case?

**Comment by Drakulix** [comment]
Returning a 404 for pages you should not be able to access is common practice to hide api endpoints an attack shall no know about. But that makes only sense for api endpoints the user cannot know about, not for once, like editing a project, where he does, but actually has no permission. So yes this is a little bit problematic.

**Comment by henderkes** [comment]
I'm currently fixing this by declaring a PermissionDenied errorhandler

**Comment by henderkes** [comment]
Should a user know that the /delete/ endpoint exists? I guess not, so delete = 404 and update without permissions = 403?
