### ISSUE TITLE
[BE] Deleting a bookmark doesn't work

### ISSUE THREAD

**Issue by suzanap** [Drakulix/knex#268]
The response I get from Postman when I try to delete a bookmark for a user:

[deleteBookmarks.txt](https://github.com/Drakulix/knex/files/1117456/deleteBookmarks.txt)
![pasted image at 2017_07_02 12_24 am](https://user-images.githubusercontent.com/28600681/27765834-a83d851c-5ebd-11e7-8a4b-047371a65f46.png)

**Comment by pdler** [comment]
The remove_bookmark() function gives the correct return value now
