### ISSUE TITLE
[BE] User API getUser

### ISSUE THREAD

**Issue by pdler** [Drakulix/knex#270]
The json file only gives the roles as id value. But we need the roles as String

**Comment by henderkes** [comment]
Can you elaborate a bit? The /api/users GET call?

**Comment by pdler** [comment]
Yes, we only have a call which gives us a user with given email address. A call that gives us all user does still not exist or? The /api/users GET call gives a json which contains the roles as id. The frontend does not knows which id means an admin or user? So it will be better if the roles field contains the roles as string instead of an id.

Btw: the json contains the hashed password. it will be better if you remove this field in the /api/users GET call

**Comment by henderkes** [comment]
Alright, I have no idea how to get the corresponding strings attached to that role (not sure if they even exist by default) but I will update once this is fixed

**Comment by Drakulix** [comment]
@DubbleClick I think this is only of interested to know, if the user is an admin or not ( right? @pdler ).
So if we can match that and just add a field called "is_admin" or something like that, that should be enough.

**Comment by henderkes** [comment]
I thought about it a bit and strongly consider implementing our own permission checks and just completely forgetting about Flasks stuff except for the login. That way we can define id and roles to our liking and aren't bound to ReferenceFields with no documentation. I might try that later and if it gets too complicated I'll just define a secondary ListField role_names.
