### ISSUE TITLE
[BE] Added endpoints for improved User Experience

### ISSUE THREAD

**Issue by mharasic** [Drakulix/knex#274]
Following endpoints are needed for improved functionality:

getProjectInformationForUser (currentUser, projectID)
regular result for project with ID
bookmarked state of project for currentUser (true/false)
is user author of project (true/false)

all tags of all projects, the current user is author of 
result [list of tags]

for notification list is the title of the projects needed as well as the regular information

**Comment by henderkes** [comment]
done in #294, will close this once merged
