### ISSUE TITLE
API Wiki

### ISSUE THREAD

**Issue by markwitz** [Drakulix/knex#28]
pease review:
[Wiki](https://github.com/Drakulix/knex/wiki/API)

**Comment by markwitz** [comment]
how do we handle json5 input? 
Context-Type: application/json5 ?

**Comment by Drakulix** [comment]
Yes JSON5 is handled by a special mime-type where accepted.

Overall I think the error codes are too simple. An internal server error for example is always possible. Other error types should be added where appropriate.

```
@app.route('/api/projects/add', methods=['PUT'])
onError: 404
```
Should be just /api/projects
Error code cannot be 404, the project does not exist.
Either `BadRequest` or `InternalServerError` (depending on the validity of the json(5).

```
@app.route('/api/projects/search', methods=['POST'])

{
  "query": {
  }
}
```

Why that query field there, is that actually ES-syntax? Just use the query object itself, no need to wrap it.

**Comment by JamesComey** [comment]
Guys can we please only use GET and POST, I tried to do a delete query and couldn't get it working. I used HttpRequester(firefox addon) and it just didn't work... No clue if it is the addon or flask or whatever...

Lets just use
/api/projects/add
/api/projects/edit/id
/api/projects/delete/id
...
instead?  =) 
Not sure if, but I guess it will also be simpler for the frontend team... come on let's do this ^^

**Comment by Drakulix** [comment]
no please use restful naming conventions. @JamesComey please try Postman and if that still does not work we can make an exception for the delete call only.
