### ISSUE TITLE
[BE] POST to /api/users/<email:mail> returns wrong uuid for bookmarks.

### ISSUE THREAD

**Issue by gitmirgut** [Drakulix/knex#291]
The uuid of the bookmarks returned form endpoint ` /api/users/<email:mail>` are wrong.
The returned `uuid`'s are similar to `b0dcf91bff5b4b27bc0db2dcfe343e70`, but they have to look like this
`b0dcf91b-ff5b-4b27-bc0d-b2dcfe343e70`. (This is similar to issue #122)

**Comment by henderkes** [comment]
fixing this in #280

**Comment by henderkes** [comment]
edit: changes are too severe either way, will have to do it in another branch but after #280 and #286 are merged (due to other changes in the branches, would lead to a very very nasty rebase)

**Comment by henderkes** [comment]
actually this might already be fixed in #286 since I implemented a to_dict method for the User class which casts everything to string before returning the response

**Comment by henderkes** [comment]
yes it is fixed 
![image](https://user-images.githubusercontent.com/7896469/27990219-bc88de12-644f-11e7-98a8-e66ac3d38fc2.png)
