### ISSUE TITLE
[BE / FE] '/api/users' POST doesn't require login

### ISSUE THREAD

**Issue by henderkes** [Drakulix/knex#292]
register function - yeah. I still see this as an issue and as far as I understood we didn't yet agree on a solution

**Comment by aTepliak** [comment]
Wasn't the decision to pull all @login required  functions in app.py so taht    __init__.py  contains only main method (because in  actual init.py @login seem to work with post)?

**Comment by henderkes** [comment]
@login_required also works in blueprints, just @roles_required('...') doesn't
@login_required is also needed for user calls, get projects, put projects, etc. just for some reason not post_users

**Comment by Drakulix** [comment]
to be able to register. this was now the decision.

**Comment by henderkes** [comment]
it's very easily abusable though and literally the only call that doesn't require a login, can't the FE proxy the creation over a preset user or something?

**Comment by Drakulix** [comment]
It could be abusable, but it is meant to be self-hosted for now. This should at best be configurable. But that is up to fixing #282, until then we allow it.
