### ISSUE TITLE
[BE] validator doesn't care about 'required' and 'additionalProperties: false" in definitions

### ISSUE THREAD

**Issue by henderkes** [Drakulix/knex#299]
yeah this is an issue because it will validate pretty much anything as comment list, as long as it's a list of jsons in any format you like

**Comment by markwitz** [comment]
have you checked if the no additional parameter settings are on the proper layer like we discussed on Wednesday?

**Comment by henderkes** [comment]
didn't yet, I'll do once I come to it

**Comment by henderkes** [comment]
oh this is fixed already
