### ISSUE TITLE
TODOS FE

### ISSUE THREAD

**Issue by mharasic** [Drakulix/knex#300]
- [ ] Upload Avatar

- [ ] Click on notification link with comment should open the comments in its project as well

- [x] **Saved searches have to be connected to BE** 
  - [x] SavedQueries.jsx ComponentWillMount(){ //TODO LOAD all queries for User
  - [x] SavedQuery.jsx  deleteQuery
  - [x] SearchPage saveSearch()
  - [x] SearchPage loadQuery with ID

- [x] Links for Tags (Chips) in
  - [x] ProfileContainer
  - [x] ProjectContainer
  - [x] Wrong LINK

**Comment by JamesComey** [comment]
Concerning the links to tags, lets use a structure like /discovery?tag=TAG,
Then we can parse the tag and put it into the filter.

**Comment by mharasic** [comment]
URLS have to be at least one according to schema

**Comment by henderkes** [comment]
Add multi file upload to this, worst case just send the binaries as files[]. It's essentially the same as the avatar upload (which I still battle with but should be done today) edit: avatar can be tested now

**Comment by henderkes** [comment]
![image](https://user-images.githubusercontent.com/7896469/28331592-f4977904-6bf1-11e7-8a25-1a46e4afc4b7.png)

Feel like this is an issue too
