### ISSUE TITLE
TODOS BE

### ISSUE THREAD

**Issue by mharasic** [Drakulix/knex#302]
- [x] Archivation of projects
    Only the admin can later on delete the project finally

Advanced search delivers archived files as well

**Comment by mharasic** [comment]
{
  "message": "'dict' object has no attribute 'email'", 
  "validation_error": null
}

**Comment by henderkes** [comment]
didn't we fix that on wednesday? did the change not make it into master yet? let me check this quick

edit: it's fixed in master as far as I can see

**Comment by henderkes** [comment]
Upload avatar is ready for testing in #313

**Comment by DubbleClick** [comment]
Not sure about number 2, I ticked it because I remember fixing it last weekend and I don't see the PR open anymore.

**Comment by henderkes** [comment]
Projects can already be archived
https://github.com/Drakulix/knex/blob/master/tests/api/test_projects.py#L341

**Comment by henderkes** [comment]
> Advanced search delivers archived files as well

You can send { archived: "true"} in the query and it will only show archived projects. With { archived: "false" } it will only show active projects. Without indication, both are returned

**Comment by mharasic** [comment]
:+1:
