### ISSUE TITLE
Deletion / Archivation of projects has to delete them form bookmarks and notifiactions as well

### ISSUE THREAD

**Issue by mharasic** [Drakulix/knex#333]

**Comment by henderkes** [comment]
it deletes them from bookmarks and notifications upon deletion, but not upon archivation
if in question, send ?archived=mixed to grab projects from notifications

**Comment by henderkes** [comment]
I consider this closed because notifications for archived projects shouldn't be deleted (I mean we even notify if someone's project was archived by someone else)
