### ISSUE TITLE
Saving of queries with date_from leads to 500

### ISSUE THREAD

**Issue by mharasic** [Drakulix/knex#364]
| [2017-07-23 15:48:46,843] ERROR in app: Exception on /api/projects/search/advanced/ [POST]
flask_1                  | Traceback (most recent call last):
flask_1                  |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
flask_1                  |     response = self.full_dispatch_request()
flask_1                  |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
flask_1                  |     rv = self.handle_user_exception(e)
flask_1                  |   File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
flask_1                  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
flask_1                  |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
flask_1                  |     reraise(exc_type, exc_value, tb)
flask_1                  |   File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
flask_1                  |     raise value
flask_1                  |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
flask_1                  |     rv = self.dispatch_request()
flask_1                  |   File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
flask_1                  |     return self.view_functions[rule.endpoint](**req.view_args)
flask_1                  |   File "/usr/local/lib/python3.5/dist-packages/flask_login/utils.py", line 228, in decorated_view
flask_1                  |     return func(*args, **kwargs)
flask_1                  |   File "/backend/api/search.py", line 145, in search_avanced
flask_1                  |     request_json['query']['filter']['bool']['must'].append(date_filter)
flask_1                  | KeyError: 'filter'

**Comment by Drakulix** [comment]
Should be fixed in #354 by commit 08ffff8
