### ISSUE TITLE
look for an open source font instead of AvenirNext

### ISSUE THREAD

**Issue by Rintel** [Drakulix/knex#38]
# Ideas

- Roboto
https://fonts.google.com/specimen/Roboto
- Advent Pro
https://fonts.google.com/specimen/Advent+Pro
- Open Sans
https://fonts.google.com/specimen/Open+Sans

**Comment by Drakulix** [comment]
Voting for Roboto and Open Sans. Advent looks too slim and worse in readability, where both Roboto and Open Sans look much cleaner.
