### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by gitmirgut** [Drakulix/knex#39]
When I try to send a `POST` request using `http://localhost:5000/api/projects/search` or a `GET` `http://localhost:5000/api/projects/dummyadd`. I get the following error message from the browser (chrome):

```post_request.html:14 XMLHttpRequest cannot load http://localhost:5000/api/projects/dummyadd. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.```

(With postman it works) 

I guess it has to do with [CORS](https://www.html5rocks.com/en/tutorials/cors/)  which has no impact on postman but on the normal browser. For testing you could use this [file](https://gist.githubusercontent.com/gitmirgut/43e54a2efb2d81b3ba887c3e61e0f5be/raw/15ea79afc11312efc637bfe88537077a1e1e8876/testing_request.html).

**Comment by gitmirgut** [comment]
If I integrate [`Flask-cors`](http://flask-cors.readthedocs.io/en/latest/) in the [flask_api.py](https://github.com/Drakulix/knex/blob/searchapi/pythonfile/flask_api.py):

```python
...
from flask_cors import CORS, cross_origin
...
es = Elasticsearch(['http://elasticsearch:9200'])
app=Flask(__name__)
CORS(app)
```
everything works fine. But I don't know if this, is the regular way to do it or if this has any impact on security.

**Comment by Drakulix** [comment]
Yes this is expected and I totally forget about it. The default settings of Flask-cors are secure and in-fact increase security of the web-api, although we may want to tweak those later down the line.

I would highly suggest, that you do a PR with your purposed changes @gitmirgut. I will merge them ASAP.
