### ISSUE TITLE
BE Search Issues

### ISSUE THREAD

**Issue by mharasic** [Drakulix/knex#419]
Advanced search only delivers 10 items ....

**Comment by Drakulix** [comment]
I have checked the es query, it does not expose any limits. Maybe my ES knowledge is not good enough, but this seems to be more of a frontend error.

**Comment by mharasic** [comment]
No ... I always get 10 results back....

**Comment by mharasic** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html#search-request-from-size
