### ISSUE TITLE
/pythonfile/flask_api.py:dummyadd at branch searchapi doesn't return a valid json. 

### ISSUE THREAD

**Issue by gitmirgut** [Drakulix/knex#45]
```json
{"_index": "projects-index", "_type": "Project", "_id": "1", "_version": 112, "result": "updated", "_shards": {"total": 2, "successful": 1, "failed": 0}, "created": false}{"_index": "projects-index", "_type": "Project", "_id": "2", "_version": 112, "result": "updated", "_shards": {"total": 2, "successful": 1, "failed": 0}, "created": false}{"_index": "projects-index", "_type": "Project", "_id": "3", "_version": 112, "result": "updated", "_shards": {"total": 2, "successful": 1, "failed": 0}, "created": false}
```
is not valid.

**Comment by JamesComey** [comment]
@gitmirgut it is not supposed to. The function just adds 3 projects to elastic search, the output is the elastic search output of the 3 insertions and is just there to show that the insertion worked. The function will be removed, but I created it so we can put projects into elasticsearch so we can test the search function... I will edit it and make it to JSON and also insert the examples Marko provided.
