### ISSUE TITLE
Evaluate ElasticSearch & take a look at alternatives

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#5]

**Comment by Drakulix** [comment]
Note: Check license

**Comment by JamesComey** [comment]
"Elasticsearch" was chosen first, but was quickly reevaluated and changed after receiving Marko's feedback. In order to have keep a minimal set of programming languages, "Whoosh", which is written in Python, was chosen to be the search engine framework of choice.
Note on Whoosh license:"This software is licensed under the terms of the simplified BSD (A.K.A. “two clause” or “FreeBSD”) license."

**Comment by Drakulix** [comment]
According to https://whoosh.readthedocs.io/en/latest/quickstart.html we need to build the index manually, which would mean updating two data storages (very error prone). Is there an integration framework for whoosh + mongodb?
Also that argument is completely irrelevant, as long as our search engine framework has nice python and mongodb bindings, which elasticsearch seemed to have.
Please elaborate on the choice of whoosh. I am really not convinced, that this is a good idea, solely based on the fact, that whoosh is written in python, which is to be honest not even an advantage, as the fastest python libraries, are all native ones, as python itself is most of the time not fast enough.

**Comment by JamesComey** [comment]
I agree with you, in my opinion it is no problem to have a JAVA search engine framework. We produce a dockerfile in the end anyway and it is not important there if we have programs in different programming languages running. Also we don't need to program JAVA as elasticsearch takes all requests in JSON and returns the results in JSON. The decission was solely based on the intervention of the CEO. If we want to keep it in Python, then Whoosh seems like a reasonable choice. That is what the decision was based on. As mentioned, the decision is not fixed. I have put it in the offer as open for discussion until milestone 1. (Not sure if this kind of information belongs here) Concerning the technical implementation, I personally have not looked into that too much. I need to get a better understanding of MongoDB and then on how to use Whoosh. Elasticsearch was looking way nicer as it seemed to have everything already in place. Maybe we should discuss this again... I will look at the MongoDB/Whoosh compatibility again.

**Comment by Drakulix** [comment]
Thanks. I will keep this issue open then and we discuss this on wednesday, when you/we have done more research on the subject.

**Comment by Drakulix** [comment]
Entscheidung: ElasticSearch
