### ISSUE TITLE
Repo structure & .gitignore & README

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#6]
Create some folders.

Maybe
  - resources
  - frontend
    - .gitignore
  - backend
    - .gitignore
  - README.md
  - .gitignore
  - bla bla bla

**Comment by markwitz** [comment]
maybe a tools/scripts folder containging usefull shellscripts for testing or setting up sample data?

**Comment by Drakulix** [comment]
Maybe as a subfolder of resources? At least that folder is what I wanted to use for sample data. Or maybe tools could be for code and resources for data?

**Comment by markwitz** [comment]
Sounds good

**Comment by Drakulix** [comment]
Closed in favor of #78
