### ISSUE TITLE
Update schema

### ISSUE THREAD

**Issue by markwitz** [Drakulix/knex#60]
- [x] analysis now array 
- [x] array on top 
- [x] make both possible array and object on top
- [ ] allow url to be (optionally? if easy) to be an array
- [x] Make nice template

**Comment by Drakulix** [comment]
- [ ] Make nice template pls.

**Comment by markwitz** [comment]
cant we always store url in an array that would make this much easier

**Comment by Drakulix** [comment]
thats why I made the `optionally?` thingy. You can just decide that.
