### ISSUE TITLE
PDF Parsing?

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#62]
- [ ] Evaluate Libraries for PDF parsing
- [ ] Maybe writeup small (backend independent) example, if it is easy to do.

**Comment by henderkes** [comment]
I've had a look and messed around with pdf parsing (extracing text) using PDFMiner (open source, not stl), I am however not entirely sure what our use case with that information would be as the result is unformatted. 
Save it within a project json?

**Comment by Drakulix** [comment]
no, just pipe it into elastic. this is mainly a research topic for later, nothing that needs to be fleshed out now.
