### ISSUE TITLE
Adjust Project POST

### ISSUE THREAD

**Issue by markwitz** [Drakulix/knex#82]
The post method has to handle multiple projects in one manifest

**Comment by markwitz** [comment]
we could need some better error text handling if one of the manifests passed fails

**Comment by gitmirgut** [comment]
After a post of a project, just the `_id` of a project is posted to elastic search. Like this it is not possible to use the api functions for search.

See **POST**: http://localhost:5000/api/projects/search
with json body:
```
{
    "query": {
        "match_all": {}
    }
}
```

**Comment by henderkes** [comment]
I'm not sure if I understand what you mean, what do you need?

**Comment by henderkes** [comment]
Edit: I just saw the es.index() call was somehow changed to a ln es.create() call with an empty body, I'll try to see where that came from and fix it asap. I'm slightly confused as to how that happened
