### ISSUE TITLE
Research Flask + User integration

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#9]
Check for frameworks that handle session management or even full user management via flask.

**Comment by svirovsk** [comment]
Some useful extensions could be:

[Flask-Login](https://flask-login.readthedocs.io/en/latest/): logging in, logging out, “remember me”-function, but no authorization
[Flask-Principal](http://pythonhosted.org/Flask-Principal/): permissions, roles
[Flask-Admin]( https://flask-admin.readthedocs.io/en/latest/): building an admin interface on top of an existing data model 
[Flask-Security]( https://pythonhosted.org/Flask-Security/): some security mechanisms; rolls up Flask-Login, Flask-Principal, Flask-WTF and other extensions 
[Flask-Session](https://pythonhosted.org/Flask-Session/): support for server-side session 
(flask default session is client-side and not secure -> https://blog.miguelgrinberg.com/post/how-secure-is-the-flask-user-session)
[Flask-KVSession]( http://pythonhosted.org/Flask-KVSession/): another possibility for server-side session, but maybe not as often used as Flask-Session

[Flask-Admin vs. Flask-Principal and Flask-Login]( http://stackoverflow.com/questions/11804922/flask-admin-flask-login-and-or-flask-principal)
[Flask-Login, Flask-Principal, Flask-Security]( http://stackoverflow.com/questions/17321520/flask-auth-principal-and-flask-security)
[Flask-Login vs. Flask-Session]( https://www.reddit.com/r/flask/comments/4ppelj/flasklogin_vs_flasksessions/)
[Flask-Session vs. default session]( http://stackoverflow.com/questions/32084646/flask-session-extension-vs-default-session)

Examples:
[User-Login with Flask-Login]( https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-v-user-logins) 
[User management with Flask-Login](https://realpython.com/blog/python/using-flask-login-for-user-management-with-flask/)
[User management with Flask-Login and MongoDB](https://runningcodes.net/flask-login-and-mongodb/)
[Storing sessions with Flask-Session and MongoDB](http://flask.pocoo.org/snippets/110/)
[Flask-Security and MongoEngine](https://pythonhosted.org/Flask-Security/quickstart.html#mongoengine-application)

**Comment by Drakulix** [comment]
Very nice write up, thank you!

The list of features of Flask-Security looks very compelling and the last example shows good MongoDB integration. It also looks like it is maintained and in a healthy state (https://github.com/mattupstate/flask-security last commit 6 days ago) and it's license is MIT.

I would suggest we use that for our user management.
