### ISSUE TITLE
[BE] Test malformed content type

### ISSUE THREAD

**Issue by Drakulix** [Drakulix/knex#97]
POST to /api/projects with Content-Type Header != "application/json" or "application/json5", but valid JSON. Should still error.

Test for BadRequest status code

Method `test_missformed_content_type` in `/tests/api/test_projects.py`

**Comment by Leats** [comment]
I tried and it gives back status code 200. Either I did a mistake with the test and am not seeing it, or the header type doesn't get checked.
See pull request #123 for code.
